CREATE TABLE IF NOT EXISTS public.participant (
    par_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    par_name character varying NOT NULL,
    par_MRN numeric(9, 0) NOT NULL,
    par_ward character varying NOT NULL,
    par_agegroup text NOT NULL,
    par_class text NOT NULL,
    CONSTRAINT par_pkey PRIMARY KEY (par_id)
);
CREATE TABLE IF NOT EXISTS public.category (
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    values_list character varying NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (category_id)
);
CREATE TABLE IF NOT EXISTS public.attendance (
    att_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    att_day character varying NOT NULL,
    att_dayofmonth character varying NOT NULL,
    att_month character varying NOT NULL,
    att_year character(4) NOT NULL,
    att_event character varying NOT NULL,
    att_list text NOT NULL,
    CONSTRAINT att_pkey PRIMARY KEY (att_id)
);