CREATE TABLE IF NOT EXISTS public.participant (
    par_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    par_name character varying NOT NULL,
    par_MRN numeric(9, 0) NOT NULL,
    par_ward character varying NOT NULL,
    par_agegroup text NOT NULL,
    par_class text NOT NULL,
    CONSTRAINT par_pkey PRIMARY KEY (par_id)
);

CREATE TABLE IF NOT EXISTS public.institute (
    class_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    class_type character varying NOT NULL,
    CONSTRAINT class_pkey PRIMARY KEY (class_id)
);

CREATE TABLE IF NOT EXISTS public.skillacquisition (
    skill_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    skill_type character varying NOT NULL,
    CONSTRAINT skill_pkey PRIMARY KEY (skill_id)
);